{{ if .Values.corePackages.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: core-packages
type: Opaque
data:
  azurestorageaccountname: {{ .Values.corePackages.storageAccountName }}
  azurestorageaccountkey: {{ .Values.corePackages.storageAccountKey }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: binary-core-packages
spec:
  storageClassName: {{ .Values.corePackages.storageClass }}
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.corePackages.storageClass }}
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: binary-core-packages  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: {{ .Values.corePackages.blobResourceGroupName }}
      shareName: {{ .Values.corePackages.shareName }}
    nodeStageSecretRef:
      name: core-packages
      namespace: {{ .Release.Namespace }}
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binary-core-packages
spec:
  storageClassName: {{ .Values.corePackages.storageClass }}
  volumeName: binary-core-packages
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-core-packages
spec:
  storageClassName: {{ .Values.corePackages.storageClass }}
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.corePackages.storageClass }}
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: website-core-packages  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: {{ .Values.corePackages.blobResourceGroupName }}
      shareName: {{ .Values.corePackages.websiteShareName }}
    nodeStageSecretRef:
      name: core-packages
      namespace: {{ .Release.Namespace }}
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-core-packages
spec:
  storageClassName: {{ .Values.corePackages.storageClass }}
  volumeName: website-core-packages
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
{{ end }}
