apiVersion: v1
description: An acme settings chart for Jenkins infra project
name: acme
version: 0.1.3
home: "https://github.com/jenkins-infra/charts"
maintainers:
  - name: Olblak
    email: me@olblak.com
    url: https://github.com/olblak
