{{- if not .Values.existingServiceAccount }}
# From https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.serviceAccountName" . }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "jenkins.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
