on:
  pull_request:
    types:
      - opened
      # - synchronize # ? https://github.com/orgs/community/discussions/25796
    paths:
      - 'charts/**'
  push:
    branches-ignore:    
      - 'main'
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_BOT_TOKEN }}

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - id: configuregit
        name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - id: nextversion
        name: next release version
        uses: jenkins-x-plugins/jx-release-version@v2.6.11

      - name: do something with the next version
        run: echo next version is $VERSION
        env:
          VERSION: ${{ steps.nextversion.outputs.version }}
