name: Check chart version bump
on:
  push: null
  pull_request: null
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: list_modified_chart_folders
        name: List modified chart folders
        # if: github.ref != 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path' | grep "^charts/" | xargs dirname | cut -d "/" -f 2 | sort --unique > modified_chart_folders.txt
          
          echo "= cat modified_chart_folders.txt"
          cat modified_chart_folders.txt
          
          # Store the modified folders as a step output
          # echo "modified_chart_folders=$(cat modified_chart_folders.txt)" >> $GITHUB_OUTPUT
          {
            echo 'modified_chart_folders<<EOF'
            cat modified_chart_folders.txt
            echo EOF
          } >> "$GITHUB_ENV"
      - id: check-bump
        name: Check if every modified chart version has been bumped
        if: github.ref != 'refs/heads/main'
        run: |
          echo "= Check if every modified chart version has been bumped"
          printf '%s\n' "$modified_chart_folders"
          
          PR_BRANCH=${GITHUB_REF#refs/pull/*/merge}
          MAIN_BRANCH=${GITHUB_REF#refs/heads/}
          echo "== PR_BRANCH: ${PR_BRANCH}:"
          echo "== MAIN_BRANCH: ${MAIN_BRANCH}:"
          echo "== GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"

          for folder in $modified_chart_folders; do
            echo "== folder: ${folder}:"
            echo "== github.event.before: ${{ github.event.before }}"
            MAIN_CHART_VERSION=$(git show origin:charts/$folder/Chart.yaml | grep "^version:")
            PR_CHART_VERSION=$(git show ${{ github.event.before }}:charts/$folder/Chart.yaml | grep "^version:")
            echo "== MAIN_CHART_VERSION: ${MAIN_CHART_VERSION}:"
            echo "== PR_CHART_VERSION: ${PR_CHART_VERSION}:"

            if [ "$MAIN_CHART_VERSION" == "$PR_CHART_VERSION" ]; then
              echo "ERROR: the version of the '${folder}' chart hasn't been bumped."
              # exit 1
            fi

            echo "The version of the '${folder}' chart has been bumped."
          done
