name: Test Charts
on:
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch: null
env:
  UNITTEST_VERSION: v0.3.4
jobs:
  find-modified-charts-with-unit-tests:
    runs-on: ubuntu-latest
    outputs:
      charts_matrix: ${{ steps.list_modified_charts_with_unit_tests.outputs.modified_charts_with_unit_tests }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - id: list_modified_charts_with_unit_tests
        name: List modified charts with unit tests
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "== start"
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "= PR"
            # Retrieve the list of modified chart names in the pull request
            modifiedChartPaths=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path' | xargs dirname | cut -d "/" -f1-2 | grep "^charts/" | sort --unique)
          else
            # TODO: Retrieve only the list of modified chart names in the last commit
            echo "= diff name-only"
            git diff --name-only
            echo "= diff name-only"
            git diff --name-only 
            # Retrieve all charts
            modifiedChartPaths=$(find . -maxdepth 2 -type d | cut -d "/" -f2-3 | grep "^charts/" | sort --unique)
          fi

          # Keep only modified charts with unit tests
          modifiedChartsWithUnitTests=()
          for chartName in "$modifiedChartPaths"; do
              path="${chartName}/tests"
              if [ -d "$path" ]; then
                  modifiedChartsWithUnitTests+=("$(echo $chartName | cut -d '/' -f 2)")
              fi
          done

          if [ -n "$modifiedChartsWithUnitTests" ]; then
            # Transform the array into a JSON
            jsonArray=$(printf "%s\n" "${modifiedChartsWithUnitTests[@]}" | jq --raw-input --slurp 'split("\n") | map(select(length > 0))' | tr -d '\n')
            jsonContent="{\"chart\": ${jsonArray}}"

            # Store the JSON as step output
            echo "modified_charts_with_unit_tests=$jsonContent" >> "$GITHUB_OUTPUT"
          else
            echo "= no modified chart with unit tests found."
            # Store the JSON as step output
            echo "modified_charts_with_unit_tests=''" >> "$GITHUB_OUTPUT"
          fi

  unit-tests:
    runs-on: ubuntu-latest
    needs: find-modified-charts-with-unit-tests
    if: ${{ needs.find-modified-charts-with-unit-tests.outputs.charts_matrix != '' }}  # Without it, the strategy parser will fail if the changed_directories is empty.
    strategy:
      matrix: ${{fromJson(needs.find-modified-charts-with-unit-tests.outputs.charts_matrix)}}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Tools Versions
        id: tools-versions
        run: |
          current_helm_version="$(curl --silent --location https://raw.githubusercontent.com/jenkins-infra/docker-helmfile/main/Dockerfile  | grep 'ARG' | grep 'HELM_VERSION=' | sort -u | cut -d'=' -f2)"
          echo "CURRENT_HELM_VERSION=${current_helm_version}" >> $GITHUB_OUTPUT
      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
        with:
          version: "${{ steps.tools-versions.outputs.CURRENT_HELM_VERSION }}"
      - name: install helm unittests
        run: |
          helm env
          # Repeat 2 times to fight against network errors in  GHA runners
          # Always return true
          helm plugin install https://github.com/helm-unittest/helm-unittest --version ${UNITTEST_VERSION} \
            || helm plugin install https://github.com/helm-unittest/helm-unittest --version ${UNITTEST_VERSION} \
            || true
          # Fail if not installed
          helm plugin list | grep unittest
      - name: run unit tests
        working-directory: ./charts/
        run: |
          helm unittest "${{ matrix.chart }}"
